addSbtPlugin("com.47deg"                 % "sbt-org-policies" % "0.13.1")
addSbtPlugin("com.47deg"                 % "sbt-microsites"   % "1.1.3")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"    % "0.9.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"    % "1.6.1")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"         % "2.1.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"     % "0.1.11")
